### ISSUE TITLE
Megan.glb geometry is incorrect

### ISSUE THREAD

**Issue by lenkawell** [warrenm/GLTFKit2#11]
Loading the attached Megan.glb does not display correctly in GLTFViewer. 

Works OK in https://gltf-viewer.donmccurdy.com

[Megan.glb.zip](https://github.com/warrenm/GLTFKit2/files/7782090/Megan.glb.zip)

**Comment by warrenm** [comment]
This should be resolved as of 4e8b3f9.

**Comment by lenkawell** [comment]
That fixes it, thanks very much!
