### ISSUE TITLE
Fox.glb does not display correctly

### ISSUE THREAD

**Issue by lenkawell** [warrenm/GLTFKit2#12]
The attached Fox.glb file does not display correctly in GLTFViewer. 

Displays OK in https://gltf-viewer.donmccurdy.com

[Fox.glb.zip](https://github.com/warrenm/GLTFKit2/files/7782098/Fox.glb.zip)

**Comment by warrenm** [comment]
This should be resolved as of 4e8b3f9.

**Comment by lenkawell** [comment]
That fixes it, thanks very much!
