### ISSUE TITLE
GLB models are having no textures and solid colours

### ISSUE THREAD

**Issue by JGVB** [warrenm/GLTFKit2#15]
The sample project works fine, but when the source code is imported into my project, this is the result. It happens for all glbs that I have tested so far.

![Screenshot 2022-02-23 at 15 55 54](https://user-images.githubusercontent.com/3453556/155407128-4b1dfe40-949c-4807-bc86-907213c5b73a.jpeg)

Any ideas as to why?

**Comment by warrenm** [comment]
Nope. If you can attach a complete project that manifests this issue, I'll try to investigate.

**Comment by JGVB** [comment]
I extracted the code from my project related to displaying this 3d and put it into a new project (along with your source code)....and it worked.  Seems like it's something with my project settings? My work is cut out!

**Comment by JGVB** [comment]
I had the pod GLTFSceneKit in my project. Though removing it did not fix the issue, I'm wondering if this is causing some conflict.

**Comment by JGVB** [comment]
The issue was PrefersOpenGL = true in plist.  Removing this (usign Metal) fixed it

**Comment by warrenm** [comment]
Good to know; thanks for following up.
