### ISSUE TITLE
Error when runing macOS viewer example

### ISSUE THREAD

**Issue by opchronatron** [warrenm/GLTFKit2#16]
`Reason: tried: '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/GLTFKit2.framework/Versions/A/GLTFKit2' (code signature in <30041B46-B48F-3C9E-ADC3-85F3133B3B6B> '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/GLTFKit2.framework/Versions/A/GLTFKit2' not valid for use in process: mapping process has no Team ID and is not a platform binary), '/usr/lib/swift/GLTFKit2.framework/Versions/A/GLTFKit2' (no such file), '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/glTF Viewer.app/Contents/MacOS/../Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' (code signature in <30041B46-B48F-3C9E-ADC3-85F3133B3B6B> '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/glTF Viewer.app/Contents/Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/GLTFKit2.framework/Versions/A/GLTFKit2' (no such file), '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/glTF Viewer.app/Contents/MacOS/../Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' (code signature in <30041B46-B48F-3C9E-ADC3-85F3133B3B6B> '/Users//Library/Developer/Xcode/DerivedData/GLTFKit2-hjeduxuqrgncgqaweyjkstyyxmlt/Build/Products/Debug/glTF Viewer.app/Contents/Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' (no such file), '/System/Library/Frameworks/GLTFKit2.framework/Versions/A/GLTFKit2' (no such file)`

**Comment by warrenm** [comment]
It looks like the framework is being built and embedded, but the signing identity is invalid. You probably need to configure the GLTFKit2 and GLTFViewer projects to use your own credentials in the "Signing & Capabilities" tab in the project settings.

As of b7fa15b, these settings have been defaulted in the relevant targets, so you may receive a more helpful error message after pulling.

This issue will be autoclosed in 7 days if no response is received.

**Comment by warrenm** [comment]
Closing.
