### ISSUE TITLE
Implement EXT_meshopt_compression decompression

### ISSUE THREAD

**Issue by berbschloe** [warrenm/GLTFKit2#22]
I'm having an issue loading a GLB file that is compressed with Meshopt (EXT_meshopt_compression).

[Smilies_20220815.glb.zip](https://github.com/warrenm/GLTFKit2/files/9365799/Smilies_20220815.glb.zip) 

It is crashing on the load step.
![Screen Shot 2022-08-17 at 11 08 38 AM](https://user-images.githubusercontent.com/5903560/185248615-72bacb2d-d189-45fb-9469-fcbf143f9fc3.png)

Would it be possible get support for loading these files (similar to Draco)?

If not, is there a way to check if a compression is used on a GLB file so I can pop up an alert saying "unsupported"?
Thanks in advance for any support.

**Comment by warrenm** [comment]
Sorry about the crash. We should definitely be better about checking required extensions so we don't blow up in cases like this.

Much like Draco, I'm not interested in taking meshoptimizer on as a hard dependency, but I imagine a similar plugin approach would work. If you have opinions on what that should look like, I'm open to proposals.

I don't have any bandwidth to actually fix this this month, though, just to set expectations.

**Comment by warrenm** [comment]
Required extension validation is implemented in 382b798.

**Comment by berbschloe** [comment]
Thanks for getting back to me, for the time being I'm filtering out any `GLTFAsset` that have any `extensionsRequired` and throwing an error.

**Comment by donmccurdy** [comment]
> Much like Draco, I'm not interested in taking meshoptimizer on as a hard dependency, but I imagine a similar plugin approach would work. If you have opinions on what that should look like, I'm open to proposals.

Unlike Draco, it is very possible to implement Meshopt decompression without any dependencies. The project provides an unoptimized "reference" implementation in 300 lines of JavaScript:

https://github.com/zeux/meshoptimizer/blob/master/js/meshopt_decoder_reference.js

**Comment by warrenm** [comment]
Hey @donmccurdy, thanks for the note. This makes me more comfortable with including meshopt decompression in GLTFKit2 core. Will investigate for future implementation.

**Comment by warrenm** [comment]
EXT_meshopt_compression is supported as of ebfee4a.

**Comment by warrenm** [comment]
This issue will be closed as completed in seven days if no further feedback is received.

**Comment by warrenm** [comment]
Closing as complete.
