### ISSUE TITLE
Wrong mesh winding for negative scaled nodes

### ISSUE THREAD

**Issue by abbaswasim** [warrenm/GLTFKit2#26]
This is `GLTFKit` issue and haven't tried `GLTFKit2` yet but I have a feeling (quick search didn't find the fix) this project will be suffering from the same issue too and since this one is the newer I am creating issue here.

The issue is that according to glTF spec:

```
When a mesh primitive uses any triangle-based topology (i.e., triangles, triangle strip, or triangle fan), the determinant of the node’s global transform defines the winding order of that primitive. If the determinant is a positive value, the winding order triangle faces is counterclockwise; in the opposite case, the winding order is clockwise.
```

I have tried GLTFKit with [unit_cube.zip](https://github.com/warrenm/GLTFKit2/files/10269804/unit_cube.zip) model to show the issue. You will see an inside out cube.

**Comment by warrenm** [comment]
This is a renderer-level concern, and GLTFKit2 doesn't provide any renderers. It seems that SceneKit, which is used in the sample viewer included with this project, handles this situation correctly.
<img width="912" alt="Screenshot 2022-12-20 at 9 26 16 AM" src="https://user-images.githubusercontent.com/39937547/208729014-ad682b2e-5dd6-4878-b396-4eccfa451a1c.png">

**Comment by abbaswasim** [comment]
humn, interesting. I saw the issue in `GLTFKit` which does provide a viewer so assumed it might exist here too.
<img width="912" alt="Screenshot 2022-12-20 at 20 04 30" src="https://user-images.githubusercontent.com/5260991/208756382-eae09b58-afd5-40b8-8945-a4a7242dcb4f.png">

**Comment by warrenm** [comment]
Feel free to file an issue against the appropriate project. Closing.
