### ISSUE TITLE
RealityKit support

### ISSUE THREAD

**Issue by FreakTheMighty** [warrenm/GLTFKit2#27]
Any thoughts on what it would take to provide RealityKit support? This would be useful for ARKit development.

**Comment by warrenm** [comment]
It will certainly be nontrivial, partially because of the number of features to be implemented, and partially because RealityKit has a bias toward USD(Z). What use cases do you have that aren't addressed by [Reality Converter](https://developer.apple.com/augmented-reality/tools/)?

**Comment by FreakTheMighty** [comment]
USDZ may be the way to go, but we are dealing with user generated content that will need to be converted to USDZ. The ecosystem for this doesn't seem great. It seems like most of Apple's investments are going to RealityKit so I'm concerned starting a new project with SceneKit.

**Comment by issacclee** [comment]
Same here, we produce massive amount of gltf with custom data embedded in "extra". We run apple's usdconvert CLI on our server to convert gltf to usdz, which would strip away those extra information or any custom gltf extension.

A full fledge gltf loader for realitykit would be a great add on to the entire realitykit ecosystem.

**Comment by FreakTheMighty** [comment]
I would echo @issacclee regarding extensibility in glb. We need to support custom vertex attributes and while I'm not sure if this library currently supports them I know the format does and that it __could__ be added. USDZ on the other hand will not be extensible.

For our use case we currently only need geometry + hierarchy + custom vertex attributes.

**Comment by issacclee** [comment]
> I would echo @issacclee regarding extensibility in glb. We need to support custom vertex attributes and while I'm not sure if this library currently supports them I know the format does and that it **could** be added. USDZ on the other hand will not be extensible.
> 
> For our use case we currently only need geometry + hierarchy + custom vertex attributes.

It seems like RealityKit do expose great deal of low level api for us to write a GLTF loader...do you have any ideas on that? Although I'm not a swift guru, but I'm certainly willing to help.

Also, checkout this repo https://github.com/schwa/SwiftGLTF

**Comment by warrenm** [comment]
Jonathan's project is definitely worth a look, and the code is tidy, but it's far from complete. I've begun looking into this myself, and I have a rough idea of how to go about this, but it's going to take quite a bit more work.
<img width="592" alt="A very simple glTF 2.0 asset loaded by the in-progress RealityKit converter" src="https://user-images.githubusercontent.com/39937547/217365020-8e711415-65b6-49db-b15f-139ee27b0b73.png">

**Comment by FreakTheMighty** [comment]
@warrenm thats awesome! Any chance you have that in a branch. We may be able to test and contribute improvements.

**Comment by warrenm** [comment]
Nothing published yet. Stay tuned.

**Comment by warrenm** [comment]
We have helmet.
<img width="592" alt="Screenshot 2023-02-07 at 4 25 03 PM" src="https://user-images.githubusercontent.com/39937547/217397457-cc362d06-ed8b-455e-a606-f59ac1ace4f7.png">

**Comment by warrenm** [comment]
Initial support for RealityKit conversion available in 50ea450.

Basic usage is:
```swift
let asset = try GLTFAsset(url: assetURL)
if let scene = asset.defaultScene {
    let rootEntity = GLTFRealityKitLoader.convert(scene: scene)
    let worldOriginAnchor = AnchorEntity()
    arView.scene.addAnchor(worldOriginAnchor)
    worldOriginAnchor.addChild(rootEntity)
}
```

Feedback welcome.

**Comment by issacclee** [comment]
> Initial support for RealityKit conversion available in [50ea450](https://github.com/warrenm/GLTFKit2/commit/50ea450508d2dcfe1a26dad2b096bae94a9d810b).
> 
> Basic usage is:
> 
> ```swift
> let asset = try GLTFAsset(url: assetURL)
> if let scene = asset.defaultScene {
>     let rootEntity = GLTFRealityKitLoader.convert(scene: scene)
>     let worldOriginAnchor = AnchorEntity()
>     arView.scene.addAnchor(worldOriginAnchor)
>     worldOriginAnchor.addChild(rootEntity)
> }
> ```
> 
> Feedback welcome.

That's excellent work, I'll look into it later today and see what I can contribute.

**Comment by FreakTheMighty** [comment]
@warrenm I'm getting a fatal error while unwrapping an optional nil value using [this file](https://drive.google.com/file/d/1ZrqgBuGvWAdzLh1aY-mdeehQCzvC9r8W/view?usp=share_link). Apologies for the size, I don't have a smaller repro ATM.

The exception throws at this line https://github.com/warrenm/GLTFKit2/blob/50ea450508d2dcfe1a26dad2b096bae94a9d810b/GLTFKit2/GLTFKit2/GLTFRealityKit.swift#L282

**Comment by FreakTheMighty** [comment]
With this pull request the model load! https://github.com/warrenm/GLTFKit2/pull/28

**Comment by warrenm** [comment]
At this point we're well on our way to supporting RealityKit conversion. In the interest of being able to track individual problems as they arise, and file PRs against them, please create _new issues_ with any problems you encounter. Thanks for the discussion so far!
