### ISSUE TITLE
Incorrect color of the face

### ISSUE THREAD

**Issue by hi-yox** [warrenm/GLTFKit2#29]
Hello, this project is great, but I have a problem, after obtaining blendshape information from Google's mediapipe, using SCNMorpher to set the weight will cause incorrect color of the face. Could you please help to check.

The first picture is correct, No lights were used

<img width="700" alt="Screenshot 2023-06-02 at 09 22 12" src="https://github.com/warrenm/GLTFKit2/assets/8189379/e6fa950c-d2a1-4f13-bd57-f525cdbbbb9b">

<img width="613" alt="Screenshot 2023-06-02 at 09 24 23" src="https://github.com/warrenm/GLTFKit2/assets/8189379/d5f64569-682d-4e46-a0e3-6a636e6e4be3">

**Comment by warrenm** [comment]
This might be at least partially addressed by 7f64669. Please give it a try and let me know if it helps.

**Comment by hi-yox** [comment]
Thank you so much. Perfect solution to my problem;

**Comment by warrenm** [comment]
Glad to hear it worked. Thanks for the confirmation
