### ISSUE TITLE
How add opacity from model?

### ISSUE THREAD

**Issue by kourion11** [warrenm/GLTFKit2#31]
When adding transparency to the model, it does not work..

**Comment by warrenm** [comment]
Please describe what you’re trying to do, provide the exact steps you’re taking, and if possible, provide a glTF file that illustrates the issue.

**Comment by kourion11** [comment]
I do this:
let source = GLTFSCNSceneSource(asset: asset)
  if let defaultScene = source.defaultScene {
  let node = defaultScene.rootNode
  node.opacity = 0.3

**Comment by warrenm** [comment]
This issue has nothing to do with GLTFKit2. I recommend learning about blend modes, transparency modes, and related topics in SceneKit, and asking questions on StackOverflow if you continue to have difficulty.

**Comment by kourion11** [comment]
> This issue has nothing to do with GLTFKit2. I recommend learning about blend modes, transparency modes, and related topics in SceneKit, and asking questions on StackOverflow if you continue to have difficulty.

Ok, thanks
