### ISSUE TITLE
Support for KHR_texture_basisu

### ISSUE THREAD

**Issue by ClayQAQ** [warrenm/GLTFKit2#35]
Would it be possible to support KHR_texture_basisu?

**Comment by warrenm** [comment]
KHR_texture_basisu support is now available as of [156537f](https://github.com/warrenm/GLTFKit2/commit/156537f7d3f26d7ca8e61b593bbce3f508d021b9). Please consult the [relevant section of the README](https://github.com/warrenm/GLTFKit2#using-ktx2-with-basis-universal) for implementation details.

**Comment by ClayQAQ** [comment]
OK. Your coding efficiency is incredible.
