### ISSUE TITLE
Model broke app

### ISSUE THREAD

**Issue by kourion11** [warrenm/GLTFKit2#41]
After recent updates, this model started dropping app...
In gltfViever it also gives an error
[Uploading CiroModel.glb.zip…]()
<img width="837" alt="Снимок экрана 2023-10-11 в 14 00 21" src="https://github.com/warrenm/GLTFKit2/assets/77104848/e1b340b9-8dc1-48bb-8867-b305677e67db">

**Comment by warrenm** [comment]
It looks like your sample asset didn't upload fully. Can you share another link?

**Comment by kourion11** [comment]
> It looks like your sample asset didn't upload fully. Can you share another link?

Sorry
[CiroModel.glb.zip](https://github.com/warrenm/GLTFKit2/files/12872279/CiroModel.glb.zip)

**Comment by warrenm** [comment]
By the way, with crashes like this, it's extremely helpful if you can share a complete backtrace instead of just the crash message.

**Comment by kourion11** [comment]
<img width="901" alt="Снимок экрана 2023-10-11 в 19 26 36" src="https://github.com/warrenm/GLTFKit2/assets/77104848/10c09685-f2ec-4350-8b61-2916b1256324">

Thread 1: "*** -[__NSArrayM objectAtIndexedSubscript:]: index 9223372036854775807 beyond bounds [0 .. 35]"

**Comment by kourion11** [comment]
> By the way, with crashes like this, it's extremely helpful if you can share a complete backtrace instead of just the crash message.

I just had a problem with this model before, it displayed very strangely. Then after talking to a 3D modeler we realized that the problem was in the Color Attribute that was added in one of the 3D editors and after removing Color Attribute from the model everything worked fine.

Maybe this information will be useful in some way

**Comment by warrenm** [comment]
There's still something wrong with the rendering that I'll continue to investigate, but I've pushed a change that should fix the crash. Very sorry about that.

**Comment by kourion11** [comment]
> There's still something wrong with the rendering that I'll continue to investigate, but I've pushed a change that should fix the crash. Very sorry about that.

It's all right! Thank you for your work!

**Comment by warrenm** [comment]
I've [implemented better handling of normalized integer accessors](https://github.com/warrenm/GLTFKit2/commit/02cb28fbcdb1fbdf63fce9b7740095e09e392afc), which fixes the rendering errors I was seeing with this model. I would note that if you have a vertex color attribute whose contents is solid white for all vertices, it's wasteful to include it in the exported model. But at least now it will render correctly!

**Comment by kourion11** [comment]
> I've [implemented better handling of normalized integer accessors](https://github.com/warrenm/GLTFKit2/commit/02cb28fbcdb1fbdf63fce9b7740095e09e392afc), which fixes the rendering errors I was seeing with this model. I would note that if you have a vertex color attribute whose contents is solid white for all vertices, it's wasteful to include it in the exported model. But at least now it will render correctly!

It got better! Thank you!

**Comment by warrenm** [comment]
Thank you for your recent issue reports. You have an uncanny knack for exposing edge cases that I have long known to be problematic, but that I didn't have sufficient motivation to investigate.

**Comment by warrenm** [comment]
Is this issue fully resolved or is there some other action needed to resolve it?

**Comment by kourion11** [comment]
> Thank you for your recent issue reports. You have an uncanny knack for exposing edge cases that I have long known to be problematic, but that I didn't have sufficient motivation to investigate.

Glad I could help!

**Comment by kourion11** [comment]
> Is this issue fully resolved or is there some other action needed to resolve it?

Yeah, problem solved. Thank you!
