### ISSUE TITLE
Add Mac Catalyst Xcode Destination

### ISSUE THREAD

**Issue by lenkawell** [warrenm/GLTFKit2#47]
Could you please add Mac Catalyst to your list of Supported Destinations in the Xcode project? It works fine and it would make pulling changes just a little easier. Thanks!

**Comment by warrenm** [comment]
Mac Catalyst (and tvOS) are now available as supported destinations (a909aacb). These updates have been incorporated into release [0.5.6](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.6). Please let me know if these updates serve your purposes.

**Comment by lenkawell** [comment]
Just what I was looking for. Thank you very much!

**Comment by warrenm** [comment]
Certainly. Glad to hear it.
