### ISSUE TITLE
Crash when converting model containing 8-bit sparse accessor indices

### ISSUE THREAD

**Issue by kourion11** [warrenm/GLTFKit2#52]
Hi, it gives an error and crashes the application when using this model
Error:
`Assertion failed: (accessor.sparse.indexComponentType == GLTFComponentTypeUnsignedShort || accessor.sparse.indexComponentType == GLTFComponentTypeUnsignedInt), function GLTFSCNPackedDataForAccessor, file GLTFSceneKit.m, line 321.`
Model:
[avatar_1705565985793.glb.zip](https://github.com/warrenm/GLTFKit2/files/13986617/avatar_1705565985793.glb.zip)

**Comment by warrenm** [comment]
This sounds like a duplicate of #49. Make sure you've updated to at least 1bbc10e or version [0.5.7](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.7).

**Comment by kourion11** [comment]
Sorry for a duplicate!
Thank you!

**Comment by warrenm** [comment]
Thanks for confirming!

**Comment by kourion11** [comment]
Unfortunately in version 0.5.7 the same thing happens( 
Can you please check this model for me?
