### ISSUE TITLE
GPU instancing extension support?

### ISSUE THREAD

**Issue by jessearmandse** [warrenm/GLTFKit2#54]
Hello, 

I was trying to load a simple model that supports `EXT_mesh_gpu_instancing`, as can be seen in [SimpleInstancing](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/SimpleInstancing) model.

Also, found out that there are at two fixes related to this from `cgltf` [#185](https://github.com/jkuhlmann/cgltf/pull/185) and [#216](https://github.com/jkuhlmann/cgltf/pull/216).

I applied those fixes, then tried to load the model again, but what I see is this instead:

<img width="912" alt="Screenshot 2024-02-15 at 5 35 18 PM" src="https://github.com/warrenm/GLTFKit2/assets/79617396/2593103d-5c7b-4912-9c3e-45f9a970506e">

However, the model can be loaded normally in [three-gltf-viewer](https://github.com/donmccurdy/three-gltf-viewer), as can be seen here:

<img width="1707" alt="Screenshot 2024-02-15 at 5 36 55 PM" src="https://github.com/warrenm/GLTFKit2/assets/79617396/481ad128-4b24-49b4-8c6c-d53cdb85738e">

Any idea what's wrong, and what could be done to load and render the same model?

**Comment by warrenm** [comment]
What's wrong is that we don't support `EXT_mesh_gpu_instancing` yet, and neither SceneKit nor RealityKit support instanced user attributes, so adding this will take some work.

**Comment by warrenm** [comment]
Preliminary support for mesh instancing is available as of 6c4d05d and will be incorporated in a forthcoming release. Any feedback welcome.

<img width="912" alt="instancing" src="https://github.com/warrenm/GLTFKit2/assets/39937547/99a0f1ef-0121-42d9-9e87-ee57367b7e47">

**Comment by jessearmandse** [comment]
Right, I discovered that it wasn't supported after looking through the `GLTFSceneKit`. Thanks for the quick response, I'll try out the changes.

**Comment by warrenm** [comment]
This enhancement has been incorporated into the [0.5.9 release](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.9).

This issue will be closed as completed in 7 days if no further feedback is received.

**Comment by warrenm** [comment]
Closing.
