### ISSUE TITLE
App crashes on iOS 15.x device stating dyld[7200]: Symbol not found:

### ISSUE THREAD

**Issue by kaustubh-seachange** [warrenm/GLTFKit2#61]
`dyld[7200]: Symbol not found: (_$sSo17OS_dispatch_queueC8DispatchE12asyncAndWait7executexxyKXE_tKlF)
  Referenced from: '/private/var/containers/Bundle/Application/046636B7-AAB5-4F75-8921-E027A0865CCC/ABCiOS.app/Frameworks/GLTFKit2.framework/GLTFKit2'
  Expected in: '/usr/lib/swift/libswiftDispatch.dylib'
Message from debugger: killed`

The above message is logged when I try to launch the app which uses GLTFKit2 as dependency to render glb models.

Environment: XCode 15.3, iOS 15.8.2 and iPhone 6S device.

Please note the same code worked for latest device like iPhone 12.

On investigation found the cause of above issue is this line in GLTFRealityKit.swift at line 376

`return DispatchQueue.main.asyncAndWait  {
     return convert(scene: scene, asset: asset)
  }`

After commenting above code app worked fine on iPhone 6S device albeit without rendering the glb model.

**Comment by warrenm** [comment]
Thanks for the report. We stopped using that API in c28cbf8, but there hasn't been a public release since that change. I'll release v0.5.11 incorporating recent changes momentarily.

**Comment by warrenm** [comment]
Version [0.5.11](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.11) has now been released.

**Comment by kaustubh-seachange** [comment]
Verified the changes in 0.5.11, app doesnt crashes on iPhone 6S (iOS 15.8.2) devices.

**Comment by warrenm** [comment]
Thanks for verifying!
