### ISSUE TITLE
GLTF Export missing

### ISSUE THREAD

**Issue by daniel-packard** [warrenm/GLTFKit2#9]
Hello @warrenm - we're looking for a way to export an SCNScene to gltf/glb formats. 

According to the readme:
> GLTFKit2 is an efficient glTF loader **and exporter** for Objective-C and Swift.

But it looks like an objective-c wrapper for the "exporter" part of cgltf has not been implemented yet.

Do you have plans to implement soon and/or are you looking for contributions? 

PS: Really enjoyed your Metal by Example material!

**Comment by warrenm** [comment]
The readme is more aspirational than actual. Export support isn’t on the immediate roadmap, but we can use this issue to discuss the baseline export feature set you’d like to use.

**Comment by daniel-packard** [comment]
Thanks! 

We're looking to export static triangular meshes with a single base texture. 

(no animation, rigging, metallic textures, etc)

**Comment by daniel-packard** [comment]
FYI - we have the option to do the format conversion on our server, so that's what we will do for now

But we're still very much interested in a mobile library for converting to gltf on the client. We'll keep an eye on your development plans and would be happy to pitch in. 

(we = the https://www.spectre3d.io/ team)

**Comment by warrenm** [comment]
Appreciate the additional details, and sorry to have created false hope. I’ve laid the groundwork for export, but it’ll be a while yet before it supports even your basic use cases. I’ll make export of core features a priority as time allows.
